services:
  auth:
    container_name: AuthServer
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AuthPg: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      Auth__Issuer: "http://localhost:5000"
      Auth__ApplyMigrationsOnStartup: "true"
      Seed__Clients__WebSpa__ClientId: ${WEBSPA_CLIENT_ID}
      Seed__Clients__SvcExample__ClientId: ${SVC_EXAMPLE_CLIENT_ID}
      Seed__Clients__SvcExample__ClientSecret: ${SVC_EXAMPLE_SECRET}
      OIDCProviders__Yandex__ClientId: ${YANDEX_CLIENT_ID}
      OIDCProviders__Yandex__ClientSecret: ${YANDEX_CLIENT_SECRET}
      OIDCProviders__VkId__ClientId: ${VKID_CLIENT_ID}
      OIDCProviders__VkId__ClientSecret: ${VKID_CLIENT_SECRET}
    ports:
      - "5000:8080"
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine3.22
    container_name: PostgresDB
    restart: unless-stopped
    env_file:
        - .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        # внутри сети compose Postgres всегда на 5432; наружу — только для локальной отладки
        - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
        - pg_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 10

volumes:
  pg_data:
